### ISSUE TITLE
🐛 Fix Palette Generation Issues

### ISSUE THREAD

**Issue by arvindcheenu** [arvindcheenu/matercolor#3]
### Todo
- [ ] Fix redundant palette generation with NaN inputs
- [ ] Update the Example Documentation

**Comment by arvindcheenu** [comment]
- [x] Fixed in the Latest Commit to Master. 
- [x] Updated Example Documentation
- [x] Bumped Version to 1.0.2 (Patch)
